
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaoeabhtbynyfzyfzogp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhb2VhYmh0YnlueWZ6eWZ6b2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MjQzNzksImV4cCI6MjA2MjEwMDM3OX0.hqJiwG2IQindO2LVBg4Rhn42FvcuZGAAzr8qDMhFBTQ";

// Create a custom storage implementation that falls back to memory storage if localStorage isn't available
const createFallbackStorage = () => {
  // In-memory storage fallback
  const inMemoryStorage = new Map<string, string>();
  console.log("Initializing fallback storage mechanism");
  
  return {
    getItem: (key: string) => {
      try {
        // Try localStorage first
        const localStorageValue = localStorage.getItem(key);
        if (localStorageValue !== null) {
          return localStorageValue;
        }
        
        // Fall back to in-memory if needed
        return inMemoryStorage.get(key) || null;
      } catch (error) {
        console.log('Storage getItem fallback used:', key);
        return inMemoryStorage.get(key) || null;
      }
    },
    setItem: (key: string, value: string) => {
      try {
        // Try localStorage first
        localStorage.setItem(key, value);
      } catch (error) {
        console.log('Storage setItem fallback used:', key);
        inMemoryStorage.set(key, value);
      }
    },
    removeItem: (key: string) => {
      try {
        // Try localStorage first
        localStorage.removeItem(key);
      } catch (error) {
        console.log('Storage removeItem fallback used:', key);
        inMemoryStorage.delete(key);
      }
    },
    clear: () => {
      try {
        localStorage.clear();
      } catch (error) {
        console.log('Storage clear fallback used');
        inMemoryStorage.clear();
      }
    }
  };
};

// Create and export the supabase client with proper typing
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: createFallbackStorage(),
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false, // Prevent auto-detection of OAuth redirects to avoid loops
      flowType: 'implicit', // Use implicit flow instead of PKCE to be more resilient
      debug: process.env.NODE_ENV === 'development' // Enable debug logs in development only
    },
    global: {
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY,
        'Content-Type': 'application/json'
      }
    }
  }
);

// Add a listener to log auth state changes for debugging
// But limit the frequency of logged events to prevent console spam
let lastAuthEvent = '';
let lastAuthEventTime = 0;

supabase.auth.onAuthStateChange((event, session) => {
  const now = Date.now();
  // Only log if different event or same event but after 1 second
  if (event !== lastAuthEvent || (now - lastAuthEventTime) > 1000) {
    console.log('Auth state changed:', event, session ? 'Session exists' : 'No session');
    lastAuthEvent = event;
    lastAuthEventTime = now;
  }
});

// Export a helper function to clear auth state in case of corruption
export const resetAuthState = async () => {
  try {
    await supabase.auth.signOut({ scope: 'local' });
    return { success: true };
  } catch (error) {
    console.error('Error resetting auth state:', error);
    return { success: false, error };
  }
};

// Export a function to check if session is valid (without triggering refresh)
export const isSessionValid = async () => {
  try {
    const { data } = await supabase.auth.getSession();
    return !!data.session;
  } catch (error) {
    console.error('Error checking session validity:', error);
    return false;
  }
};
